version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env

  # customer:
  #   build: ./src/ms-customer
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     RABBITMQ_URL: amqp://user:password@rabbitmq
  #     RABBITMQ_QUEUE_NAME: customer_queue

  # harbor-management:
  #   build: ./src/ms-ship
  #   ports:
  #     - '3001:3001'
  #   environment:
  #     RABBITMQ_URL: amqp://user:password@rabbitmq
  #     RABBITMQ_QUEUE_NAME: harbor_management_queue

  # Add other microservices containers here
